spring:
  redis:
    cluster:
      nodes: wangziming.xin:7000,wangziming.xin:7001,wangziming.xin:7002, wangziming.xin:7003,wangziming.xin:7004,wangziming.xin:7005
      max-redirects: 3
    password: 1993wang
    timeout: 3000
    jedis:
      pool:
        max-active: 20
        max-idle: 8

logging:
  level:
    root: INFO
    org.springframework.data.redis: INFO